#ifndef FUNCTIONS_H
#define FUNCTIONS_H

#define FIELD(reg, fld)		(((reg) & fld##_Msk) >> fld##_Pos)

/*** USART ***/

/* receive and dispatch interrupts for `usart` */
void usart_interrupt(struct mcu_usart *usart);

/* enable and configure `usart` interface with `baud_rate_hz` frequency */
void usart_init(struct mcu_usart *usart, uint32_t baud_hz, pinout_t tx, pintout_t rx);

/*** GPIO ***/

typdef struct {
	strucg mcu_gpio *gpio;
	uint8_t pin;
	uint8_t altfn;
} pinout_t;

static inline void
gpio_enable(struct mcu_gpio *gpio)
{
	if (gpio == GPIOA)
		RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	if (gpio == GPIOB)
		RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	if (gpio == GPIOC)
		RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	if (gpio == GPIOD)
		RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
	if (gpio == GPIOE)
		RCC->AHB1ENR |= RCC_AHB1ENR_GPIOEEN;
	if (gpio == GPIOH)
		RCC->AHB1ENR |= RCC_AHB1ENR_GPIOHEN;
}

static inline void
gpio_set_altfn(struct mcu_gpio *gpio, uint8_t pin, uint8_t altfn)
{
	/* setup the port in alternate function mode */
	gpio->MODER = (gpio->MODER & ~GPIO_MODER_MODER_Msk(pin))
	 | GPIO_MODER_MODER_ALTERNATE(pin);

	/* set the actual mode */
	gpio->AFR = (gpio->AFR & ~GPIO_AFR_AFR_Msk(pin))
	 | altfn << GPIO_AFR_AFR_Pos(pin);
}

#define PINOUT_PA8_MCO_1			((pinout_t){ GPIOA,  8, 0 })
#define PINOUT_PA13_JTMS			((pinout_t){ GPIOA, 13, 0 })
#define PINOUT_PA13_SWDIO			((pinout_t){ GPIOA, 13, 0 })
#define PINOUT_PA14_JTMS			((pinout_t){ GPIOA, 14, 0 })
#define PINOUT_PA14_SWDIO			((pinout_t){ GPIOA, 14, 0 })
#define PINOUT_PA15_JTDI			((pinout_t){ GPIOA, 15, 0 })
#define PINOUT_PB3_JTDO				((pinout_t){ GPIOB,  3, 0 })
#define PINOUT_PB4_JTRST			((pinout_t){ GPIOB,  4, 0 })
#define PINOUT_PB15_RTC_50_HZ			((pinout_t){ GPIOB, 15, 0 })
#define PINOUT_PC9_MCO_2			((pinout_t){ GPIOC,  9, 0 })
#define PINOUT_PE2_TRACECLK			((pinout_t){ GPIOE,  2, 0 })
#define PINOUT_PE3_TRACED0			((pinout_t){ GPIOE,  3, 0 })
#define PINOUT_PE4_TRACED1			((pinout_t){ GPIOE,  4, 0 })
#define PINOUT_PE5_TRACED2			((pinout_t){ GPIOE,  5, 0 })
#define PINOUT_PE6_TRACED3			((pinout_t){ GPIOE,  6, 0 })

#define PINOUT_PA0_TIM2_CH1			((pinout_t){ GPIOA,  0, 1 })
#define PINOUT_PA0_TIM2_ETR			((pinout_t){ GPIOA,  0, 1 })
#define PINOUT_PA1_TIM2_CH2			((pinout_t){ GPIOA,  1, 1 })
#define PINOUT_PA2_TIM2_CH3			((pinout_t){ GPIOA,  2, 1 })
#define PINOUT_PA3_TIM2_CH4			((pinout_t){ GPIOA,  3, 1 })
#define PINOUT_PA5_TIM2_CH1			((pinout_t){ GPIOA,  5, 1 })
#define PINOUT_PA6_TIM2_ETR			((pinout_t){ GPIOA,  5, 1 })
#define PINOUT_PA6_TIM1_BKIN			((pinout_t){ GPIOA,  6, 1 })
#define PINOUT_PA7_TIM1_CH1N			((pinout_t){ GPIOA,  7, 1 })
#define PINOUT_PA8_TIM1_CH1			((pinout_t){ GPIOA,  8, 1 })
#define PINOUT_PA9_TIM1_CH2			((pinout_t){ GPIOA,  9, 1 })
#define PINOUT_PA10_TIM1_CH3			((pinout_t){ GPIOA, 10, 1 })
#define PINOUT_PA11_TIM1_CH4			((pinout_t){ GPIOA, 11, 1 })
#define PINOUT_PA12_TIM1_ETR			((pinout_t){ GPIOA, 12, 1 })
#define PINOUT_PA15_TIM2_CH1			((pinout_t){ GPIOA, 15, 1 })
#define PINOUT_PA15_TIM2_ETR			((pinout_t){ GPIOA, 15, 1 })
#define PINOUT_PB0_TIM1_CH2N			((pinout_t){ GPIOB,  0, 1 })
#define PINOUT_PB1_TIM1_CH3N			((pinout_t){ GPIOB,  1, 1 })
#define PINOUT_PB3_TIM2_CH2			((pinout_t){ GPIOB,  3, 1 })
#define PINOUT_PB10_TIM2_CH3			((pinout_t){ GPIOB, 10, 1 })
#define PINOUT_PB11_TIM2_CH4			((pinout_t){ GPIOB, 11, 1 })
#define PINOUT_PB12_TIM1_BKIN			((pinout_t){ GPIOB, 12, 1 })
#define PINOUT_PB13_TIM1_CH1N			((pinout_t){ GPIOB, 13, 1 })
#define PINOUT_PB14_TIM1_CH2N			((pinout_t){ GPIOB, 14, 1 })
#define PINOUT_PB15_TIM1_CH3N			((pinout_t){ GPIOB, 15, 1 })
#define PINOUT_PE7_TIM1_ETR			((pinout_t){ GPIOE,  7, 1 })
#define PINOUT_PE8_TIM1_CH1N			((pinout_t){ GPIOE,  8, 1 })
#define PINOUT_PE9_TIM1_CH1			((pinout_t){ GPIOE,  9, 1 })
#define PINOUT_PE10_TIM1_CH2N			((pinout_t){ GPIOE, 10, 1 })
#define PINOUT_PE11_TIM1_CH2			((pinout_t){ GPIOE, 11, 1 })
#define PINOUT_PE12_TIM1_CH3N			((pinout_t){ GPIOE, 12, 1 })
#define PINOUT_PE13_TIM1_CH3			((pinout_t){ GPIOE, 13, 1 })
#define PINOUT_PE14_TIM1_CH4			((pinout_t){ GPIOE, 14, 1 })
#define PINOUT_PE15_TIM1_BKIN			((pinout_t){ GPIOE, 15, 1 })

#define PINOUT_PA0_TIM5_CH1			((pinout_t){ GPIOA,  0, 2 })
#define PINOUT_PA1_TIM5_CH2			((pinout_t){ GPIOA,  1, 2 })
#define PINOUT_PA2_TIM5_CH3			((pinout_t){ GPIOA,  2, 2 })
#define PINOUT_PA3_TIM5_CH4			((pinout_t){ GPIOA,  3, 2 })
#define PINOUT_PA6_TIM3_CH1			((pinout_t){ GPIOA,  6, 2 })
#define PINOUT_PA7_TIM3_CH2			((pinout_t){ GPIOA,  7, 2 })
#define PINOUT_PB0_TIM3_CH3			((pinout_t){ GPIOB,  0, 2 })
#define PINOUT_PB1_TIM3_CH4			((pinout_t){ GPIOB,  1, 2 })
#define PINOUT_PB4_TIM3_CH1			((pinout_t){ GPIOB,  4, 2 })
#define PINOUT_PB5_TIM3_CH2			((pinout_t){ GPIOB,  5, 2 })
#define PINOUT_PB6_TIM4_CH1			((pinout_t){ GPIOB,  6, 2 })
#define PINOUT_PB7_TIM4_CH2			((pinout_t){ GPIOB,  7, 2 })
#define PINOUT_PB8_TIM4_CH3			((pinout_t){ GPIOB,  8, 2 })
#define PINOUT_PB9_TIM4_CH4			((pinout_t){ GPIOB,  9, 2 })
#define PINOUT_PC6_TIM3_CH1			((pinout_t){ GPIOC,  6, 2 })
#define PINOUT_PC7_TIM3_CH2			((pinout_t){ GPIOC,  7, 2 })
#define PINOUT_PC8_TIM3_CH3			((pinout_t){ GPIOC,  8, 2 })
#define PINOUT_PC9_TIM3_CH4			((pinout_t){ GPIOC,  9, 2 })
#define PINOUT_PD2_TIM3_ETR			((pinout_t){ GPIOD,  2, 2 })
#define PINOUT_PD12_TIM4_CH1			((pinout_t){ GPIOD, 12, 2 })
#define PINOUT_PD13_TIM4_CH2			((pinout_t){ GPIOD, 13, 2 })
#define PINOUT_PD14_TIM4_CH3			((pinout_t){ GPIOD, 14, 2 })
#define PINOUT_PD15_TIM4_CH4			((pinout_t){ GPIOD, 15, 2 })
#define PINOUT_PD16_TIM4_ETR			((pinout_t){ GPIOD, 16, 2 })

#define PINOUT_PA2_TIM9_CH1			((pinout_t){ GPIOA,  2, 3 })
#define PINOUT_PA3_TIM9_CH2			((pinout_t){ GPIOA,  3, 3 })
#define PINOUT_PB8_TIM10_CH1			((pinout_t){ GPIOB,  8, 3 })
#define PINOUT_PB9_TIM11_CH1			((pinout_t){ GPIOB,  9, 3 })
#define PINOUT_PE5_TIM9_CH1			((pinout_t){ GPIOE,  5, 3 })
#define PINOUT_PE6_TIM9_CH2			((pinout_t){ GPIOE,  6, 3 })

#define PINOUT_PA8_I2C3_SCL			((pinout_t){ GPIOA,  8, 4 })
#define PINOUT_PA9_I2C3_SMBA			((pinout_t){ GPIOA,  9, 4 })
#define PINOUT_PB5_I2C1_SMBA			((pinout_t){ GPIOB,  5, 4 })
#define PINOUT_PB6_I2C1_SCL			((pinout_t){ GPIOB,  6, 4 })
#define PINOUT_PB7_I2C1_SDA			((pinout_t){ GPIOB,  7, 4 })
#define PINOUT_PB8_I2C1_SCL			((pinout_t){ GPIOB,  8, 4 })
#define PINOUT_PB9_I2C1_SDA			((pinout_t){ GPIOB,  9, 4 })
#define PINOUT_PB10_I2C2_SCL			((pinout_t){ GPIOB, 10, 4 })
#define PINOUT_PB11_I2C2_SDA			((pinout_t){ GPIOB, 11, 4 })
#define PINOUT_PB12_I2C2_SMBA			((pinout_t){ GPIOB, 12, 4 })
#define PINOUT_PC9_I2C3_SDA			((pinout_t){ GPIOC,  9, 4 })

#define PINOUT_PA1_SPI4_MOSI			((pinout_t){ GPIOA,  1, 5 })
#define PINOUT_PA1_I2S4_SD			((pinout_t){ GPIOA,  1, 5 })
#define PINOUT_PA2_I2S2_CKIN			((pinout_t){ GPIOA,  2, 5 })
#define PINOUT_PA3_I2S2_MCK			((pinout_t){ GPIOA,  3, 5 })
#define PINOUT_PA4_SPI1_NSS			((pinout_t){ GPIOA,  4, 5 })
#define PINOUT_PA4_I2S1_WS			((pinout_t){ GPIOA,  4, 5 })
#define PINOUT_PA5_SPI1_SCK			((pinout_t){ GPIOA,  5, 5 })
#define PINOUT_PA5_I2S1_CK			((pinout_t){ GPIOA,  5, 5 })
#define PINOUT_PA6_SPI1_MISO			((pinout_t){ GPIOA,  6, 5 })
#define PINOUT_PA7_SPI1_MOSI			((pinout_t){ GPIOA,  7, 5 })
#define PINOUT_PA7_I2S1_SD			((pinout_t){ GPIOA,  7, 5 })
#define PINOUT_PA15_SPI1_NSS			((pinout_t){ GPIOA, 15, 5 })
#define PINOUT_PA15_SPI1_WS			((pinout_t){ GPIOA, 15, 5 })
#define PINOUT_PB3_SPI1_SCK			((pinout_t){ GPIOB,  3, 5 })
#define PINOUT_PB3_I2S1_CK			((pinout_t){ GPIOB,  3, 5 })
#define PINOUT_PB4_SPI1_MISO			((pinout_t){ GPIOB,  4, 5 })
#define PINOUT_PB5_SPI1_MOSI			((pinout_t){ GPIOB,  5, 5 })
#define PINOUT_PB5_I2S1_SD			((pinout_t){ GPIOB,  5, 5 })
#define PINOUT_PB9_SPI2_NSS			((pinout_t){ GPIOB,  9, 5 })
#define PINOUT_PB9_I2S2_WS			((pinout_t){ GPIOB,  9, 5 })
#define PINOUT_PB10_SPI2_SCK			((pinout_t){ GPIOB, 10, 5 })
#define PINOUT_PB10_I2S2_CK			((pinout_t){ GPIOB, 10, 5 })
#define PINOUT_PB11_I2S2_CKIN			((pinout_t){ GPIOB, 11, 5 })
#define PINOUT_PB12_SPI2_NSS			((pinout_t){ GPIOB, 12, 5 })
#define PINOUT_PB12_I2S2_WS			((pinout_t){ GPIOB, 12, 5 })
#define PINOUT_PB13_SPI2_SCK			((pinout_t){ GPIOB, 13, 5 })
#define PINOUT_PB13_I2S2_CK			((pinout_t){ GPIOB, 13, 5 })
#define PINOUT_PB14_SPI2_MISO			((pinout_t){ GPIOB, 14, 5 })
#define PINOUT_PB15_SPI2_MOSI			((pinout_t){ GPIOB, 15, 5 })
#define PINOUT_PB15_I2S2_SD			((pinout_t){ GPIOB, 15, 5 })
#define PINOUT_PC2_SPI2_MISO			((pinout_t){ GPIOC,  2, 5 })
#define PINOUT_PC3_SPI2_MOSI			((pinout_t){ GPIOC,  3, 5 })
#define PINOUT_PC3_I2S2_SD			((pinout_t){ GPIOC,  3, 5 })
#define PINOUT_PC6_I2S2_MCK			((pinout_t){ GPIOC,  6, 5 })
#define PINOUT_PC7_SPI2_SCK			((pinout_t){ GPIOC,  7, 5 })
#define PINOUT_PC7_I2S2_CK			((pinout_t){ GPIOC,  7, 5 })
#define PINOUT_PC9_I2S2_CKIN			((pinout_t){ GPIOC,  9, 5 })
#define PINOUT_PC11_I2S3EXT_SD			((pinout_t){ GPIOC, 11, 5 })
#define PINOUT_PD3_SPI2_SCK			((pinout_t){ GPIOD,  3, 5 })
#define PINOUT_PD3_I2S2_CK			((pinout_t){ GPIOD,  3, 5 })
#define PINOUT_PD6_SPI3_MOSI			((pinout_t){ GPIOD,  6, 5 })
#define PINOUT_PD6_I2S3_SD			((pinout_t){ GPIOD,  6, 5 })
#define PINOUT_PE2_SPI4_SCK			((pinout_t){ GPIOE,  2, 5 })
#define PINOUT_PE4_SPI4_NSS			((pinout_t){ GPIOE,  4, 5 })
#define PINOUT_PE4_I2S4_WS			((pinout_t){ GPIOE,  4, 5 })
#define PINOUT_PE5_SPI4_MISO			((pinout_t){ GPIOE,  5, 5 })
#define PINOUT_PE6_SPI4_MOSI			((pinout_t){ GPIOE,  6, 5 })
#define PINOUT_PE6_I2S4_SD			((pinout_t){ GPIOE,  6, 5 })
#define PINOUT_PE11_SPI4_NSS			((pinout_t){ GPIOE, 11, 5 })
#define PINOUT_PE11_I2S4_WS			((pinout_t){ GPIOE, 11, 5 })
#define PINOUT_PE12_SPI4_SCK			((pinout_t){ GPIOE, 12, 5 })
#define PINOUT_PE12_I2S4_CK			((pinout_t){ GPIOE, 12, 5 })
#define PINOUT_PE13_SPI4_MISO			((pinout_t){ GPIOE, 13, 5 })
#define PINOUT_PE14_SPI4_MOSI			((pinout_t){ GPIOE, 14, 5 })
#define PINOUT_PE14_I2S4_SD			((pinout_t){ GPIOE, 14, 5 })

#define PINOUT_PA4_SPI3_NSS			((pinout_t){ GPIOA,  4, 6 })
#define PINOUT_PA4_I2S3_WS			((pinout_t){ GPIOA,  4, 6 })
#define PINOUT_PA6_SPI2_MCK			((pinout_t){ GPIOA,  6, 6 })
#define PINOUT_PA10_SPI5_MOSI			((pinout_t){ GPIOA, 10, 6 })
#define PINOUT_PA10_I2S5_SD			((pinout_t){ GPIOA, 10, 6 })
#define PINOUT_PA11_SPI4_MISO			((pinout_t){ GPIOA, 11, 6 })
#define PINOUT_PA12_SPI5_MISO			((pinout_t){ GPIOA, 12, 6 })
#define PINOUT_PA15_SPI3_NSS			((pinout_t){ GPIOA, 15, 6 })
#define PINOUT_PA15_I2S3_WS			((pinout_t){ GPIOA, 15, 6 })
#define PINOUT_PB0_SPI5_SCK			((pinout_t){ GPIOB,  0, 6 })
#define PINOUT_PB0_I2S5_CK			((pinout_t){ GPIOB,  0, 6 })
#define PINOUT_PB1_SPI5_NSS			((pinout_t){ GPIOB,  1, 6 })
#define PINOUT_PB1_I2S5_WS			((pinout_t){ GPIOB,  1, 6 })
#define PINOUT_PB3_SPI3_SCK			((pinout_t){ GPIOB,  3, 6 })
#define PINOUT_PB3_I2S3_CK			((pinout_t){ GPIOB,  3, 6 })
#define PINOUT_PB4_SPI3_MISO			((pinout_t){ GPIOB,  4, 6 })
#define PINOUT_PB5_SPI3_MOSI			((pinout_t){ GPIOB,  5, 6 })
#define PINOUT_PB5_I2S3_SD			((pinout_t){ GPIOB,  5, 6 })
#define PINOUT_PB8_SPI5_MOSI			((pinout_t){ GPIOB,  8, 6 })
#define PINOUT_PB8_I2S5_SD			((pinout_t){ GPIOB,  8, 6 })
#define PINOUT_PB10_I2S3_MCK			((pinout_t){ GPIOB, 10, 6 })
#define PINOUT_PB12_SPI4_NSS			((pinout_t){ GPIOB, 12, 6 })
#define PINOUT_PB12_I2S4_WS			((pinout_t){ GPIOB, 12, 6 })
#define PINOUT_PB13_SPI4_SCK			((pinout_t){ GPIOB, 13, 6 })
#define PINOUT_PB13_I2S4_CK			((pinout_t){ GPIOB, 13, 6 })
#define PINOUT_PB14_I2S2EXT_SD			((pinout_t){ GPIOB, 14, 6 })
#define PINOUT_PC2_I2S2EXT_SD			((pinout_t){ GPIOC,  2, 6 })
#define PINOUT_PC7_I2S3_MCK			((pinout_t){ GPIOC,  7, 6 })
#define PINOUT_PC10_SPI3_SCK			((pinout_t){ GPIOC, 10, 6 })
#define PINOUT_PC10_I2S3_CK			((pinout_t){ GPIOC, 10, 6 })
#define PINOUT_PC11_SPI3_MISO			((pinout_t){ GPIOC, 11, 6 })
#define PINOUT_PC12_SPI3_MOSI			((pinout_t){ GPIOC, 12, 6 })
#define PINOUT_PC12_I2S3_SD			((pinout_t){ GPIOC, 12, 6 })
#define PINOUT_PE2_SPI5_SCK			((pinout_t){ GPIOE,  2, 6 })
#define PINOUT_PE2_I2S5_CK			((pinout_t){ GPIOE,  2, 6 })
#define PINOUT_PE4_SPI5_NSS			((pinout_t){ GPIOE,  4, 6 })
#define PINOUT_PE4_I2S5_WS			((pinout_t){ GPIOE,  4, 6 })
#define PINOUT_PE5_SPI5_MISO			((pinout_t){ GPIOE,  5, 6 })
#define PINOUT_PE6_SPI5_MOSI			((pinout_t){ GPIOE,  6, 6 })
#define PINOUT_PE6_I2S5_SD			((pinout_t){ GPIOE,  6, 6 })
#define PINOUT_PE11_SPI5_NSS			((pinout_t){ GPIOE, 11, 6 })
#define PINOUT_PE11_I2S5_WS			((pinout_t){ GPIOE, 11, 6 })
#define PINOUT_PE12_SPI5_SCK			((pinout_t){ GPIOE, 12, 6 })
#define PINOUT_PE12_I2S5_CK			((pinout_t){ GPIOE, 12, 6 })
#define PINOUT_PE13_SPI5_MISO			((pinout_t){ GPIOE, 13, 6 })
#define PINOUT_PE14_SPI5_MOSI			((pinout_t){ GPIOE, 14, 6 })
#define PINOUT_PE14_I2S5_SD			((pinout_t){ GPIOE, 14, 6 })

#define PINOUT_PA0_USART2_CTS			((pinout_t){ GPIOA,  0, 7 })
#define PINOUT_PA1_USART2_RTS			((pinout_t){ GPIOA,  1, 7 })
#define PINOUT_PA2_USART2_TX			((pinout_t){ GPIOA,  2, 7 })
#define PINOUT_PA3_USART2_RX			((pinout_t){ GPIOA,  3, 7 })
#define PINOUT_PA4_USART2_CK			((pinout_t){ GPIOA,  4, 7 })
#define PINOUT_PA8_USART1_CK			((pinout_t){ GPIOA,  8, 7 })
#define PINOUT_PA9_USART1_TX			((pinout_t){ GPIOA,  9, 7 })
#define PINOUT_PA10_USART1_RX			((pinout_t){ GPIOA, 10, 7 })
#define PINOUT_PA11_USART1_CTS			((pinout_t){ GPIOA, 11, 7 })
#define PINOUT_PA12_USART1_RTS			((pinout_t){ GPIOA, 12, 7 })
#define PINOUT_PA15_USART1_TX			((pinout_t){ GPIOA, 15, 7 })
#define PINOUT_PB3_USART1_RX			((pinout_t){ GPIOB,  3, 7 })
#define PINOUT_PB4_I2S3EXT_SD			((pinout_t){ GPIOB,  4, 7 })
#define PINOUT_PB6_USART1_TX			((pinout_t){ GPIOB,  6, 7 })
#define PINOUT_PB7_USART1_RX			((pinout_t){ GPIOB,  7, 7 })
#define PINOUT_PB12_SPI3_SCK			((pinout_t){ GPIOB, 12, 7 })
#define PINOUT_PB12_I2S3_CK			((pinout_t){ GPIOB, 12, 7 })
#define PINOUT_PD3_USART2_CTS			((pinout_t){ GPIOD,  3, 7 })
#define PINOUT_PD4_USART2_RTS			((pinout_t){ GPIOD,  4, 7 })
#define PINOUT_PD5_USART2_TX			((pinout_t){ GPIOD,  5, 7 })
#define PINOUT_PD6_USART2_RX			((pinout_t){ GPIOD,  6, 7 })
#define PINOUT_PD7_USART2_CK			((pinout_t){ GPIOD,  7, 7 })

#define PINOUT_PA11_USART6_TX			((pinout_t){ GPIOA, 11, 8 })
#define PINOUT_PA12_USART6_RX			((pinout_t){ GPIOA, 12, 8 })
#define PINOUT_PC6_USART6_TX			((pinout_t){ GPIOC,  6, 8 })
#define PINOUT_PC7_USART6_RX			((pinout_t){ GPIOC,  7, 8 })
#define PINOUT_PC8_USART6_CK			((pinout_t){ GPIOC,  8, 8 })

#define PINOUT_PB3_I2C2_SDA			((pinout_t){ GPIOB,  3, 9 })
#define PINOUT_PB4_I2C3_SDA			((pinout_t){ GPIOB,  4, 9 })
#define PINOUT_PB8_I2C3_SDA			((pinout_t){ GPIOB,  8, 9 })
#define PINOUT_PB9_I2C2_SDA			((pinout_t){ GPIOB,  9, 9 })

#define PINOUT_PA8_USB_FS_SOF			((pinout_t){ GPIOA,  8, 10 })
#define PINOUT_PA9_USB_FS_VBUS			((pinout_t){ GPIOA,  9, 10 })
#define PINOUT_PA10_USB_FS_ID			((pinout_t){ GPIOA, 10, 10 })
#define PINOUT_PA11_USB_FS_DM			((pinout_t){ GPIOA, 11, 10 })
#define PINOUT_PA12_USB_FS_DP			((pinout_t){ GPIOA, 12, 10 })

#define PINOUT_PA6_SDIO_CMD			((pinout_t){ GPIOA,  6, 12 })
#define PINOUT_PA8_SDIO_D1			((pinout_t){ GPIOA,  8, 12 })
#define PINOUT_PA9_SDIO_D2			((pinout_t){ GPIOA,  9, 12 })
#define PINOUT_PB4_SDIO_D0			((pinout_t){ GPIOB,  4, 12 })
#define PINOUT_PB5_SDIO_D3			((pinout_t){ GPIOB,  5, 12 })
#define PINOUT_PB7_SDIO_D0			((pinout_t){ GPIOB,  7, 12 })
#define PINOUT_PB8_SDIO_D4			((pinout_t){ GPIOB,  8, 12 })
#define PINOUT_PB9_SDIO_D5			((pinout_t){ GPIOB,  9, 12 })
#define PINOUT_PB10_SDIO_D7			((pinout_t){ GPIOB, 10, 12 })
#define PINOUT_PB14_SDIO_D6			((pinout_t){ GPIOB, 14, 12 })
#define PINOUT_PB15_SDIO_CK			((pinout_t){ GPIOB, 15, 12 })
#define PINOUT_PC6_SDIO_D6			((pinout_t){ GPIOC,  6, 12 })
#define PINOUT_PC7_SDIO_D7			((pinout_t){ GPIOC,  7, 12 })
#define PINOUT_PC8_SDIO_D0			((pinout_t){ GPIOC,  8, 12 })
#define PINOUT_PC9_SDIO_D1			((pinout_t){ GPIOC,  9, 12 })
#define PINOUT_PC10_SDIO_D2			((pinout_t){ GPIOC, 10, 12 })
#define PINOUT_PC11_SDIO_D3			((pinout_t){ GPIOC, 11, 12 })
#define PINOUT_PC12_SDIO_CK			((pinout_t){ GPIOC, 12, 12 })
#define PINOUT_PD2_SDIO_CMD			((pinout_t){ GPIOD,  2, 12 })

#define PINOUT_PA0_EVENTOUT			((pinout_t){ GPIOA,  0, 15 })
#define PINOUT_PA1_EVENTOUT			((pinout_t){ GPIOA,  1, 15 })
#define PINOUT_PA2_EVENTOUT			((pinout_t){ GPIOA,  2, 15 })
#define PINOUT_PA3_EVENTOUT			((pinout_t){ GPIOA,  3, 15 })
#define PINOUT_PA4_EVENTOUT			((pinout_t){ GPIOA,  4, 15 })
#define PINOUT_PA5_EVENTOUT			((pinout_t){ GPIOA,  5, 15 })
#define PINOUT_PA6_EVENTOUT			((pinout_t){ GPIOA,  6, 15 })
#define PINOUT_PA7_EVENTOUT			((pinout_t){ GPIOA,  7, 15 })
#define PINOUT_PA8_EVENTOUT			((pinout_t){ GPIOA,  8, 15 })
#define PINOUT_PA9_EVENTOUT			((pinout_t){ GPIOA,  9, 15 })
#define PINOUT_PA10_EVENTOUT			((pinout_t){ GPIOA, 10, 15 })
#define PINOUT_PA11_EVENTOUT			((pinout_t){ GPIOA, 11, 15 })
#define PINOUT_PA12_EVENTOUT			((pinout_t){ GPIOA, 12, 15 })
#define PINOUT_PA13_EVENTOUT			((pinout_t){ GPIOA, 13, 15 })
#define PINOUT_PA14_EVENTOUT			((pinout_t){ GPIOA, 14, 15 })
#define PINOUT_PA15_EVENTOUT			((pinout_t){ GPIOA, 15, 15 })
#define PINOUT_PB0_EVENTOUT			((pinout_t){ GPIOB,  0, 15 })
#define PINOUT_PB1_EVENTOUT			((pinout_t){ GPIOB,  1, 15 })
#define PINOUT_PB2_EVENTOUT			((pinout_t){ GPIOB,  2, 15 })
#define PINOUT_PB3_EVENTOUT			((pinout_t){ GPIOB,  3, 15 })
#define PINOUT_PB4_EVENTOUT			((pinout_t){ GPIOB,  4, 15 })
#define PINOUT_PB5_EVENTOUT			((pinout_t){ GPIOB,  5, 15 })
#define PINOUT_PB6_EVENTOUT			((pinout_t){ GPIOB,  6, 15 })
#define PINOUT_PB7_EVENTOUT			((pinout_t){ GPIOB,  7, 15 })
#define PINOUT_PB8_EVENTOUT			((pinout_t){ GPIOB,  8, 15 })
#define PINOUT_PB9_EVENTOUT			((pinout_t){ GPIOB,  9, 15 })
#define PINOUT_PB10_EVENTOUT			((pinout_t){ GPIOB, 10, 15 })
#define PINOUT_PB11_EVENTOUT			((pinout_t){ GPIOB, 11, 15 })
#define PINOUT_PB12_EVENTOUT			((pinout_t){ GPIOB, 12, 15 })
#define PINOUT_PB13_EVENTOUT			((pinout_t){ GPIOB, 13, 15 })
#define PINOUT_PB14_EVENTOUT			((pinout_t){ GPIOB, 14, 15 })
#define PINOUT_PB15_EVENTOUT			((pinout_t){ GPIOB, 15, 15 })
#define PINOUT_PC0_EVENTOUT			((pinout_t){ GPIOC,  0, 15 })
#define PINOUT_PC1_EVENTOUT			((pinout_t){ GPIOC,  1, 15 })
#define PINOUT_PC2_EVENTOUT			((pinout_t){ GPIOC,  2, 15 })
#define PINOUT_PC3_EVENTOUT			((pinout_t){ GPIOC,  3, 15 })
#define PINOUT_PC4_EVENTOUT			((pinout_t){ GPIOC,  4, 15 })
#define PINOUT_PC5_EVENTOUT			((pinout_t){ GPIOC,  5, 15 })
#define PINOUT_PC6_EVENTOUT			((pinout_t){ GPIOC,  6, 15 })
#define PINOUT_PC7_EVENTOUT			((pinout_t){ GPIOC,  7, 15 })
#define PINOUT_PC8_EVENTOUT			((pinout_t){ GPIOC,  8, 15 })
#define PINOUT_PC9_EVENTOUT			((pinout_t){ GPIOC,  9, 15 })
#define PINOUT_PC10_EVENTOUT			((pinout_t){ GPIOC, 10, 15 })
#define PINOUT_PC11_EVENTOUT			((pinout_t){ GPIOC, 11, 15 })
#define PINOUT_PC12_EVENTOUT			((pinout_t){ GPIOC, 12, 15 })
#define PINOUT_PD0_EVENTOUT			((pinout_t){ GPIOD,  0, 15 })
#define PINOUT_PD1_EVENTOUT			((pinout_t){ GPIOD,  1, 15 })
#define PINOUT_PD2_EVENTOUT			((pinout_t){ GPIOD,  2, 15 })
#define PINOUT_PD3_EVENTOUT			((pinout_t){ GPIOD,  3, 15 })
#define PINOUT_PD4_EVENTOUT			((pinout_t){ GPIOD,  4, 15 })
#define PINOUT_PD5_EVENTOUT			((pinout_t){ GPIOD,  5, 15 })
#define PINOUT_PD6_EVENTOUT			((pinout_t){ GPIOD,  6, 15 })
#define PINOUT_PD7_EVENTOUT			((pinout_t){ GPIOD,  7, 15 })
#define PINOUT_PD8_EVENTOUT			((pinout_t){ GPIOD,  8, 15 })
#define PINOUT_PD9_EVENTOUT			((pinout_t){ GPIOD,  9, 15 })
#define PINOUT_PD10_EVENTOUT			((pinout_t){ GPIOD, 10, 15 })
#define PINOUT_PD11_EVENTOUT			((pinout_t){ GPIOD, 11, 15 })
#define PINOUT_PD12_EVENTOUT			((pinout_t){ GPIOD, 12, 15 })
#define PINOUT_PD13_EVENTOUT			((pinout_t){ GPIOD, 13, 15 })
#define PINOUT_PD14_EVENTOUT			((pinout_t){ GPIOD, 14, 15 })
#define PINOUT_PD15_EVENTOUT			((pinout_t){ GPIOD, 15, 15 })
#define PINOUT_PE0_EVENTOUT			((pinout_t){ GPIOE,  0, 15 })
#define PINOUT_PE1_EVENTOUT			((pinout_t){ GPIOE,  1, 15 })
#define PINOUT_PE2_EVENTOUT			((pinout_t){ GPIOE,  2, 15 })
#define PINOUT_PE3_EVENTOUT			((pinout_t){ GPIOE,  3, 15 })
#define PINOUT_PE4_EVENTOUT			((pinout_t){ GPIOE,  4, 15 })
#define PINOUT_PE5_EVENTOUT			((pinout_t){ GPIOE,  5, 15 })
#define PINOUT_PE6_EVENTOUT			((pinout_t){ GPIOE,  6, 15 })
#define PINOUT_PE7_EVENTOUT			((pinout_t){ GPIOE,  7, 15 })
#define PINOUT_PE8_EVENTOUT			((pinout_t){ GPIOE,  8, 15 })
#define PINOUT_PE9_EVENTOUT			((pinout_t){ GPIOE,  9, 15 })
#define PINOUT_PE10_EVENTOUT			((pinout_t){ GPIOE, 10, 15 })
#define PINOUT_PE11_EVENTOUT			((pinout_t){ GPIOE, 11, 15 })
#define PINOUT_PE12_EVENTOUT			((pinout_t){ GPIOE, 12, 15 })
#define PINOUT_PE13_EVENTOUT			((pinout_t){ GPIOE, 13, 15 })
#define PINOUT_PE14_EVENTOUT			((pinout_t){ GPIOE, 14, 15 })
#define PINOUT_PE15_EVENTOUT			((pinout_t){ GPIOE, 15, 15 })

#endif
